"""create PostGIS network and telemetry tables

Revision ID: 612d6a4111d6
Revises:
"""

import geoalchemy2
import sqlalchemy as sa
from alembic import op

revision = "612d6a4111d6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "routes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("train_number", sa.String(length=5), nullable=False),
        sa.Column("train_name", sa.String(length=120), nullable=False),
        sa.Column("total_distance_km", sa.Float(), nullable=False),
        sa.Column("dataset_version", sa.String(length=80), nullable=False),
        sa.Column("geometry_kind", sa.String(length=50), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="LINESTRING",
                srid=4326,
                spatial_index=False,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.CheckConstraint("total_distance_km > 0"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("train_number"),
    )
    op.create_index("idx_routes_geom", "routes", ["geom"], unique=False, postgresql_using="gist")
    op.create_table(
        "stations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("zone", sa.String(length=10), nullable=True),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                spatial_index=False,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.CheckConstraint("lat BETWEEN -90 AND 90 AND lon BETWEEN -180 AND 180"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        "idx_stations_geom", "stations", ["geom"], unique=False, postgresql_using="gist"
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("journey_id", sa.Uuid(), nullable=False),
        sa.Column("train_number", sa.String(length=5), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('speed_restriction','unscheduled_stop','congestion','weather')"
        ),
        sa.CheckConstraint("source = 'simulator'"),
        sa.CheckConstraint("severity BETWEEN 1 AND 3 AND duration_seconds BETWEEN 1 AND 3600"),
        sa.ForeignKeyConstraint(
            ["train_number"],
            ["routes.train_number"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_events_train_time", "events", ["train_number", "timestamp"], unique=False)
    op.create_table(
        "historical_delays",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("train_number", sa.String(length=5), nullable=False),
        sa.Column("station_code", sa.String(length=10), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("avg_delay_minutes", sa.Float(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.CheckConstraint("avg_delay_minutes >= 0 AND sample_count > 0"),
        sa.CheckConstraint("day_of_week BETWEEN 0 AND 6"),
        sa.ForeignKeyConstraint(
            ["station_code"],
            ["stations.code"],
        ),
        sa.ForeignKeyConstraint(
            ["train_number"],
            ["routes.train_number"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("train_number", "station_code", "day_of_week"),
    )
    op.create_table(
        "live_positions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("journey_id", sa.Uuid(), nullable=False),
        sa.Column("train_number", sa.String(length=5), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                spatial_index=False,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("distance_km", sa.Float(), nullable=False),
        sa.Column("delay_minutes", sa.Float(), nullable=False),
        sa.Column("current_speed_kmh", sa.Float(), nullable=False),
        sa.Column("last_station", sa.String(length=10), nullable=False),
        sa.Column("next_station", sa.String(length=10), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.CheckConstraint("source = 'simulator'"),
        sa.CheckConstraint("current_speed_kmh BETWEEN 0 AND 200"),
        sa.CheckConstraint("distance_km >= 0 AND delay_minutes >= 0"),
        sa.CheckConstraint("lat BETWEEN -90 AND 90 AND lon BETWEEN -180 AND 180"),
        sa.ForeignKeyConstraint(
            ["last_station"],
            ["stations.code"],
        ),
        sa.ForeignKeyConstraint(
            ["next_station"],
            ["stations.code"],
        ),
        sa.ForeignKeyConstraint(
            ["train_number"],
            ["routes.train_number"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("train_number", "journey_id", "timestamp"),
    )
    op.create_index(
        "idx_live_positions_geom", "live_positions", ["geom"], unique=False, postgresql_using="gist"
    )
    op.create_index(
        "ix_positions_journey_time", "live_positions", ["journey_id", "timestamp"], unique=False
    )
    op.create_index(
        "ix_positions_train_time", "live_positions", ["train_number", "timestamp"], unique=False
    )
    op.create_table(
        "route_stops",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("station_code", sa.String(length=10), nullable=False),
        sa.Column("arrival_seconds", sa.Integer(), nullable=True),
        sa.Column("departure_seconds", sa.Integer(), nullable=True),
        sa.Column("distance_km", sa.Float(), nullable=False),
        sa.CheckConstraint("arrival_seconds >= 0 AND departure_seconds >= 0"),
        sa.CheckConstraint("arrival_seconds IS NOT NULL OR departure_seconds IS NOT NULL"),
        sa.CheckConstraint("departure_seconds >= arrival_seconds"),
        sa.CheckConstraint("sequence >= 0 AND distance_km >= 0"),
        sa.ForeignKeyConstraint(["route_id"], ["routes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["station_code"],
            ["stations.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("route_id", "sequence"),
        sa.UniqueConstraint("route_id", "station_code"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("route_stops")
    op.drop_index("ix_positions_train_time", table_name="live_positions")
    op.drop_index("ix_positions_journey_time", table_name="live_positions")
    op.drop_index("idx_live_positions_geom", table_name="live_positions", postgresql_using="gist")
    op.drop_table("live_positions")
    op.drop_table("historical_delays")
    op.drop_index("ix_events_train_time", table_name="events")
    op.drop_table("events")
    op.drop_index("idx_stations_geom", table_name="stations", postgresql_using="gist")
    op.drop_table("stations")
    op.drop_index("idx_routes_geom", table_name="routes", postgresql_using="gist")
    op.drop_table("routes")
    # ### end Alembic commands ###
